spring:
    application:
        name: "02_CustomerService"
    datasource:
        username: root
        password: root123
        url: jdbc:mysql://localhost:3306/customer_db
        driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
    api-docs:
        enabled: true

logging:
    file:
        name: log/customers.log

server:
    port: 8080

    springdoc.swagger-ui.enabled: true
#Custom Properties - Used in application
build:
    version: "2.1"
customer:
    message: "Welcome to MSEDCL bank customer related REST API - UAT"
    contactDetails:
        name: "Snehal"
        email: "Snehal@mahadiscom.in"
    onCallSupport:
        - 9833753389
        - 9869386358

#spring.datasource.username : root
#spring.datasource.password : root123
#spring.datasource.url : jdbc:mysql://localhost:3306/customer_db
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#logging.file.name=logs/customers.log
#springdoc.swagger-ui.enabled=false
